### ISSUE TITLE
Update eigen3 to 3.3+

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball_contrib#19]
@philthiel Please update the contrib version of eigen3 to 3.3+. I have noticed that you have added 3.3.4 to the BALL-Contrib project already but the current master still uses the old 3.2.5. We require 3.3 for build error fixes with Clang (https://github.com/BALL-Project/ball/pull/648).

**Comment by philthiel** [comment]
Builds and is updated (3.3.4) in master.
